# Change these first
owner: graph8-com # Your GitHub organization or username, where this repository lives
repo: upptime-status # The name of this repository

sites:
  - name: graph8 site
    url: https://graph8.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.graph8.com
  # baseUrl: /your-repo-name
  favicon: https://graph8.com/content/images/size/w256h256/2024/06/favicon-g8.png
  faviconSvg: https://graph8.com/content/images/size/w256h256/2024/06/favicon-g8.png
  logoUrl: https://graph8.com/content/images/size/w256h256/2024/06/favicon-g8.png
  name: graph8
  introTitle: "**graph8** statuspage"
  navbar:
    - title: Status
      href: /
i18n:
  footer: graph8


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
